List<String> Ataturk_Resimleri = [
  "Ataturk_Resimleri/1.jpg",
  "Ataturk_Resimleri/2.jpg",
  "Ataturk_Resimleri/3.jpg",
  "Ataturk_Resimleri/4.jpg",
  "Ataturk_Resimleri/5.jpg",
  "Ataturk_Resimleri/6.jpg",
  "Ataturk_Resimleri/7.jpg",
  "Ataturk_Resimleri/8.jpg",
  "Ataturk_Resimleri/9.jpg",
  "Ataturk_Resimleri/10.jpg",
  "Ataturk_Resimleri/11.jpg",
  "Ataturk_Resimleri/12.jpg",
  "Ataturk_Resimleri/13.jpg",
  "Ataturk_Resimleri/14.jpg",
  "Ataturk_Resimleri/15.jpg",
  "Ataturk_Resimleri/16.jpg",
  "Ataturk_Resimleri/17.jpg",
  "Ataturk_Resimleri/18.jpg",
  "Ataturk_Resimleri/19.jpg",
  "Ataturk_Resimleri/20.jpg",
  "Ataturk_Resimleri/21.jpg",
  "Ataturk_Resimleri/22.jpg",
  "Ataturk_Resimleri/23.jpg",
  "Ataturk_Resimleri/24.jpg",
  "Ataturk_Resimleri/25.jpg",
  "Ataturk_Resimleri/26.jpg",
  "Ataturk_Resimleri/27.jpg",
  "Ataturk_Resimleri/28.jpg",
  "Ataturk_Resimleri/29.jpg",
  "Ataturk_Resimleri/30.jpg",
  "Ataturk_Resimleri/31.jpg",
  "Ataturk_Resimleri/32.jpg",
  "Ataturk_Resimleri/33.jpg",
  "Ataturk_Resimleri/34.jpg",
  "Ataturk_Resimleri/35.jpg",
  "Ataturk_Resimleri/36.jpg",
  "Ataturk_Resimleri/37.jpg",
  "Ataturk_Resimleri/38.jpg",
  "Ataturk_Resimleri/39.jpg",
  "Ataturk_Resimleri/40.jpg",
  "Ataturk_Resimleri/41.jpg",
  "Ataturk_Resimleri/42.jpg",
  "Ataturk_Resimleri/43.jpg",
  "Ataturk_Resimleri/44.jpg",
  "Ataturk_Resimleri/45.jpg",
  "Ataturk_Resimleri/46.jpg",
  "Ataturk_Resimleri/47.jpg",
  "Ataturk_Resimleri/48.jpg",
  "Ataturk_Resimleri/49.jpg",
  "Ataturk_Resimleri/50.jpg",
  "Ataturk_Resimleri/51.jpg",
  "Ataturk_Resimleri/52.jpg",
  "Ataturk_Resimleri/53.jpg",
  "Ataturk_Resimleri/54.jpg",
  "Ataturk_Resimleri/55.jpg",
  "Ataturk_Resimleri/57.jpg",
  "Ataturk_Resimleri/57.jpg",
  "Ataturk_Resimleri/58.jpg",
  "Ataturk_Resimleri/59.jpg",
  "Ataturk_Resimleri/60.jpg",
  "Ataturk_Resimleri/61.jpg",
  "Ataturk_Resimleri/62.jpg",
  "Ataturk_Resimleri/63.jpg",
  "Ataturk_Resimleri/64.jpg",
  "Ataturk_Resimleri/65.jpg",
  "Ataturk_Resimleri/66.jpg",
  "Ataturk_Resimleri/67.jpg",
  "Ataturk_Resimleri/68.jpg",
  "Ataturk_Resimleri/69.jpg",
  "Ataturk_Resimleri/70.jpg",
  "Ataturk_Resimleri/71.jpg",
  "Ataturk_Resimleri/72.jpg",
  "Ataturk_Resimleri/73.jpg",
  "Ataturk_Resimleri/74.jpg",
  "Ataturk_Resimleri/75.jpg",
  "Ataturk_Resimleri/76.jpg",
  "Ataturk_Resimleri/77.jpg",
  "Ataturk_Resimleri/78.jpg",
  "Ataturk_Resimleri/79.jpg",
  "Ataturk_Resimleri/80.jpg",
  "Ataturk_Resimleri/81.jpg",
  "Ataturk_Resimleri/82.jpg",
  "Ataturk_Resimleri/83.jpg",
  "Ataturk_Resimleri/84.jpg",
  "Ataturk_Resimleri/85.jpg",
  "Ataturk_Resimleri/86.jpg",
  "Ataturk_Resimleri/87.jpg",
  "Ataturk_Resimleri/88.jpg",
  "Ataturk_Resimleri/89.jpg",
  "Ataturk_Resimleri/90.jpg",
  "Ataturk_Resimleri/91.jpg",
  "Ataturk_Resimleri/92.jpg",
  "Ataturk_Resimleri/93.jpg",
  "Ataturk_Resimleri/94.jpg",
  "Ataturk_Resimleri/95.jpg",
  "Ataturk_Resimleri/96.jpg",
  "Ataturk_Resimleri/97.jpg",
  "Ataturk_Resimleri/98.jpg",
  "Ataturk_Resimleri/99.jpg",
  "Ataturk_Resimleri/100.jpg",
];

List<String> Bayram_29_Kutlama_Mesajlari = [
  "Kutlama_Mesajlari/1.jpg",
  "Kutlama_Mesajlari/2.jpg",
  "Kutlama_Mesajlari/3.jpg",
  "Kutlama_Mesajlari/4.jpg",
  "Kutlama_Mesajlari/5.jpg",
  "Kutlama_Mesajlari/6.jpg",
  "Kutlama_Mesajlari/7.jpg",
  "Kutlama_Mesajlari/8.jpg",
  "Kutlama_Mesajlari/9.jpg",
  "Kutlama_Mesajlari/10.jpg",
  "Kutlama_Mesajlari/11.jpg",
  "Kutlama_Mesajlari/12.jpg",
  "Kutlama_Mesajlari/13.jpg",
  "Kutlama_Mesajlari/14.jpg",
  "Kutlama_Mesajlari/15.jpg",
  "Kutlama_Mesajlari/16.jpg",
  "Kutlama_Mesajlari/17.jpg",
  "Kutlama_Mesajlari/18.jpg",
  "Kutlama_Mesajlari/19.jpg",
  "Kutlama_Mesajlari/20.jpg",
  "Kutlama_Mesajlari/21.jpg",
  "Kutlama_Mesajlari/22.jpg",
  "Kutlama_Mesajlari/23.jpg",
  "Kutlama_Mesajlari/24.jpg",
  "Kutlama_Mesajlari/25.jpg",
  "Kutlama_Mesajlari/26.jpg",
  "Kutlama_Mesajlari/27.jpg",
  "Kutlama_Mesajlari/28.jpg",
  "Kutlama_Mesajlari/29.jpg",
  "Kutlama_Mesajlari/30.jpg",
  "Kutlama_Mesajlari/31.jpg",
  "Kutlama_Mesajlari/32.jpg",
  "Kutlama_Mesajlari/33.jpg",
  "Kutlama_Mesajlari/34.jpg",
  "Kutlama_Mesajlari/35.jpg",
  "Kutlama_Mesajlari/36.jpg",
  "Kutlama_Mesajlari/37.jpg",
  "Kutlama_Mesajlari/38.jpg",
  "Kutlama_Mesajlari/39.jpg",
  "Kutlama_Mesajlari/40.jpg",
  "Kutlama_Mesajlari/41.jpg",
  "Kutlama_Mesajlari/42.jpg",
  "Kutlama_Mesajlari/43.jpg",
  "Kutlama_Mesajlari/44.jpg",
  "Kutlama_Mesajlari/45.jpg",
  "Kutlama_Mesajlari/46.jpg",
  "Kutlama_Mesajlari/47.jpg",
  "Kutlama_Mesajlari/48.jpg",
  "Kutlama_Mesajlari/49.jpg",
  "Kutlama_Mesajlari/50.jpg",
  "Kutlama_Mesajlari/51.jpg",
  "Kutlama_Mesajlari/52.jpg",
  "Kutlama_Mesajlari/53.jpg",
  "Kutlama_Mesajlari/54.jpg",
  "Kutlama_Mesajlari/55.jpg",
  "Kutlama_Mesajlari/56.jpg",
  "Kutlama_Mesajlari/57.jpg",
  "Kutlama_Mesajlari/58.jpg",
  "Kutlama_Mesajlari/59.jpg",
  "Kutlama_Mesajlari/60.jpg",
  "Kutlama_Mesajlari/61.jpg",
  "Kutlama_Mesajlari/62.jpg",
  "Kutlama_Mesajlari/63.jpg",
  "Kutlama_Mesajlari/64.jpg",
  "Kutlama_Mesajlari/65.jpg",
  "Kutlama_Mesajlari/66.jpg",
  "Kutlama_Mesajlari/67.jpg",
  "Kutlama_Mesajlari/68.jpg",
  "Kutlama_Mesajlari/69.jpg",
  "Kutlama_Mesajlari/70.jpg",
  "Kutlama_Mesajlari/71.jpg",
  "Kutlama_Mesajlari/72.jpg",
  "Kutlama_Mesajlari/73.jpg",
  "Kutlama_Mesajlari/74.gif",
  "Kutlama_Mesajlari/75.jpg",
  "Kutlama_Mesajlari/76.jpg",
  "Kutlama_Mesajlari/77.jpg",
  "Kutlama_Mesajlari/78.jpg",
  "Kutlama_Mesajlari/79.jpg",
  "Kutlama_Mesajlari/80.jpg",
  "Kutlama_Mesajlari/81.jpg",
  "Kutlama_Mesajlari/82.jpg",
  "Kutlama_Mesajlari/83.jpg",
  "Kutlama_Mesajlari/84.jpg",
  "Kutlama_Mesajlari/85.jpg",
  "Kutlama_Mesajlari/86.jpg",
  "Kutlama_Mesajlari/87.jpg",
  "Kutlama_Mesajlari/88.jpg",
  "Kutlama_Mesajlari/89.jpg",
  "Kutlama_Mesajlari/90.jpg",
  "Kutlama_Mesajlari/91.jpg",
  "Kutlama_Mesajlari/92.jpg",
  "Kutlama_Mesajlari/93.jpg",
  "Kutlama_Mesajlari/94.jpg",
  "Kutlama_Mesajlari/95.jpg",
  "Kutlama_Mesajlari/96.jpg",
  "Kutlama_Mesajlari/97.jpg",
  "Kutlama_Mesajlari/98.jpg",
  "Kutlama_Mesajlari/99.jpg",
  "Kutlama_Mesajlari/100.jpg",
];

List<String> Yazili_Kutlama_Mesajlari = [
  "Ey yükselen yeni nesil! İstikbal sizsiniz. Cumhuriyeti biz kurduk, onu yükseltecek ve yaşatacak sizsiniz.",
  "Türk milletinin karakterine ve adetlerine en uygun olan idare, Cumhuriyet idaresidir.",
  "99 yıldır ışıldayan, milletimizin geleceğini aydınlatan Cumhuriyetimizin ilelebet yaşamasını diliyor, Türk ulusunun Cumhuriyet Bayramı'nı kutluyorum.",
  "Cumhuriyetimizin kuruluşunun 98. yıl dönümü olan bu anlamlı ve özel günde, milletimizin Cumhuriyet Bayramı'nı kutluyorum.",
  "Cumhuriyet'e sahip çıkmanın onurunu yaşıyor, aziz Türk Milleti'nin 29 Ekim Cumhuriyet Bayramı'nı kutluyoruz.",
  "İstiklâl mücadelemizin önderi, Cumhuriyetimizin kurucusu Gazi Mustafa Kemal Atatürk ile silah arkadaşları başta olmak üzere bütün şehit ve gazilerimizi şükran, saygı ve rahmetle anıyoruz.",
  "Cumhuriyetimizin ilanının 99. yıl dönümü vesilesiyle, başta Gazi Mustafa Kemal Atatürk ve silah arkadaşları olmak üzere, vatanımızın aziz topraklarını canları pahasına savunan ve asil milletimizin küllerinden yeniden doğmasını sağlayan tüm şehit ve gazilerimizi rahmetle anıyorum.",
  "Cumhuriyet Bayramı güne coşku ve mutlulukla uyanmak demektir. Canım ülkem ve milletime nice mutlu, barış dolu, bütünlük içinde 29 Ekimler",
  "Cumhuriyetimizin ilanının yeni yılında Büyük Önderimiz Gazi Mustafa Kemal Atatürk”ü, aziz şehitlerimizi ve gazilerimizi saygı ve rahmetle anıyor, Cumhuriyet Bayramınızı en içten dileklerimle kutluyorum.",
  "Yirmi Dokuz Ekimi Karşılarız neşeyle çünkü bu günde erdik büyük cumhuriyete. Cumhuriyet bayramınız kutlu ve şanlı olsun.",
  "Benim nâçiz vücudum bir gün elbet toprak olacaktır. Fakat Türkiye Cumhuriyeti ilelebet payidar kalacaktır.",
  "Yirmi dokuz Ekimi Karşılarız neşeyle çünkü bu günde erdik büyük cumhuriyete. Cumhuriyet bayramınız kutlu ve şanlı olsun.",
  "Cumhuriyet Bayramı güne coşku ve mutlulukla uyanmak demektir. Canım ülkem ve milletime nice mutlu, barış dolu, bütünlük içinde 29 Ekimler",
  "29 Ekim Cumhuriyet Bayramımız kutlu olsun. Atatürk”ün çocukları olarak atamızı hasret ve özlemle anıyoruz.",
  "Cumhuriyet, demokratik bir ülkenin bozulmaz simgesidir… Cumhuriyet bayramınızı en içten duygularımla kutlarım.",
  "Cumhuriyet”in geleceğe büyük bir ümitle bakmamızı sağlayan gurur verici atılım ve başarıları, her türlü zorlu engelin aşılması konusunda bizlere güç vermesi dileğiyle. “Cumhuriyet Bayramınız Kutlu Olsun",
  "Cumhuriyet bayramı coşkusunun bütün milletimizce derinden yaşanması temennileriyle",
  "29 Ekim Cumhuriyet Bayramımız kutlu olsun. Atatürk”ün çocukları olarak atamızı hasret ve özlemle anıyoruz",
  "Biz doğrudan doğruya millet severiz ve Türk milliyetçisiyiz. Cumhuriyetimizin dayanağı, Türk topluluğudur",
  "Cumhuriyet Bayramımız kutlu olsun. Bugün her yer kırmızı beyaz olsun",
  "Cumhuriyet Bayramı”nı kutluyor, herkese esenlikler diliyorum",
  "Cumhuriyetsiz bir toplum, yarınsız bir gündür. Cumhuriyet bayramınız kutlu olsun",
  "Biz doğrudan doğruya millet severiz ve Türk milliyetçisiyiz. Cumhuriyetimizin dayanağı, Türk topluluğudur.Cumhuriyet bayramımız kutlu olsun",
  "Cumhuriyet, fikir serbestliği taraftarıdır. Samimi ve meşru olmak şartıyla her fikre hürmet ederiz.Cumhuriyet bayramımız kutlu olsun",
];
